###########
# site.title, site.url, site.author.name

title:   'Bitcoin Hard Fork Research'
author:
  name:  ''

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: /
url: https://bitcoinhardforkresearch.github.io


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

